name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Publish package
        run: |
          mvn install --batch-mode --no-transfer-progress
          mvn deploy -DskipTests -Prelease --file eolib --batch-mode --no-transfer-progress
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

  publish-github:
    needs: publish-maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version from tag
        id: get-version
        uses: battila7/get-version-action@v2
      - name: Parse Changelog
        id: changelog
        uses: coditory/changelog-parser@v1
        with:
          version: ${{ steps.get-version.outputs.version-without-v }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: EOLib v${{steps.changelog.outputs.version}}
          body: ${{ steps.changelog.outputs.description }}